exports.IpcModifiers = {
  ERROR: '-error',
  SUCCESS: '-success'
};

// Add new constants in alphabetical order
exports.IpcMessages = {
  IPC_SSF_BLUR_WINDOW: 'ssf-blur-window',
  IPC_SSF_CAPTURE_SCREEN_SNIPPET: 'ssf-capture-screen-snippet',
  IPC_SSF_CLOSE_WINDOW: 'ssf-close-window',
  IPC_SSF_FLASH_FRAME: 'ssf-flash-frame',
  IPC_SSF_FOCUS_WINDOW: 'ssf-focus-window',
  IPC_SSF_GET_WINDOW_BOUNDS: 'ssf-get-bounds',
  IPC_SSF_GET_WINDOW_ID: 'ssf-get-window-id',
  IPC_SSF_GET_WINDOW_MAXIMUM_SIZE: 'ssf-get-window-maximum-size',
  IPC_SSF_GET_WINDOW_MINIMUM_SIZE: 'ssf-get-window-minimum-size',
  IPC_SSF_GET_WINDOW_PARENT: 'ssf-get-window-parent',
  IPC_SSF_GET_WINDOW_POSITION: 'ssf-get-window-position',
  IPC_SSF_GET_WINDOW_SIZE: 'ssf-get-size',
  IPC_SSF_GET_WINDOW_TITLE: 'ssf-get-title',
  IPC_SSF_HIDE_WINDOW: 'ssf-hide-window',
  IPC_SSF_IS_WINDOW_ALWAYS_ON_TOP: 'ssf-is-window-always-on-top',
  IPC_SSF_IS_WINDOW_MAXIMIZABLE: 'ssf-is-window-maximizable',
  IPC_SSF_IS_WINDOW_MAXIMIZED: 'ssf-is-window-maximized',
  IPC_SSF_IS_WINDOW_MINIMIZABLE: 'ssf-is-window-minimizable',
  IPC_SSF_IS_WINDOW_MINIMIZED: 'ssf-is-window-minimized',
  IPC_SSF_IS_WINDOW_RESIZABLE: 'ssf-is-window-resizable',
  IPC_SSF_LOAD_URL: 'ssf-load-url',
  IPC_SSF_MAXIMIZE_WINDOW: 'ssf-maximize-window',
  IPC_SSF_MINIMIZE_WINDOW: 'ssf-minimize-window',
  IPC_SSF_NEW_WINDOW: 'ssf-new-window',
  IPC_SSF_NOTIFICATION: 'ssf-notification',
  IPC_SSF_RELOAD_WINDOW: 'ssf-reload-window',
  IPC_SSF_RESTORE_WINDOW: 'ssf-restore-window',
  IPC_SSF_SCREEN_SNIPPET_CAPTURED: 'ssf-screen-snippet-captured',
  IPC_SSF_SEND_MESSAGE: 'ssf-send-message',
  IPC_SSF_SET_WINDOW_ALWAYS_ON_TOP: 'ssf-set-window-always-on-top',
  IPC_SSF_SET_WINDOW_BOUNDS: 'ssf-set-window-bounds',
  IPC_SSF_SET_WINDOW_ICON: 'ssf-set-window-icon',
  IPC_SSF_SET_WINDOW_MAXIMIZABLE: 'ssf-set-window-maxizable',
  IPC_SSF_SET_WINDOW_MAXIMUM_SIZE: 'ssf-set-window-maximum-size',
  IPC_SSF_SET_WINDOW_MINIMIZABLE: 'ssf-set-window-minizable',
  IPC_SSF_SET_WINDOW_MINIMUM_SIZE: 'ssf-set-window-minimum-size',
  IPC_SSF_SET_WINDOW_POSITION: 'ssf-set-window-position',
  IPC_SSF_SET_WINDOW_RESIZABLE: 'ssf-set-window-resizable',
  IPC_SSF_SET_WINDOW_SIZE: 'ssf-set-window-size',
  IPC_SSF_SET_WINDOW_SKIP_TASKBAR: 'ssf-set-window-skip-taskbar',
  IPC_SSF_SHOW_WINDOW: 'ssf-show-window',
  IPC_SSF_WINDOW_EVENT: 'ssf-window-event',
  IPC_SSF_WINDOW_HAS_SHADOW: 'ssf-window-has-shadow',
  IPC_SSF_WINDOW_SUBSCRIBE_EVENTS: 'ssf-window-subscribe-events',
  IPC_SSF_UNMAXIMIZE_WINDOW: 'ssf-unmaximize-window'
};
